project:
  outputs:
    dev:
      account: <your_account>
      database: HOME_ASSIGNMENT
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 4
      type: snowflake
      user: <your_user>
      warehouse: COMPUTE_WH
  target: dev
